.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. ixcoin_qt test_ixcoin_qt
clean: FORCE
	$(MAKE) -C .. ixcoin_qt_clean test_ixcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_ixcoin_qt_check
ixcoin-qt ixcoin-qt.exe: FORCE
	 $(MAKE) -C .. ixcoin_qt
