#!/bin/bash

# This is a thin wrapper around ixcoin-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using ixcoin-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_IXCOIND

# Grab the value of $REAL_IXCOINCLI which may be ixcoin-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_BITCOINCLI}" "$@" | sed 's/\r//'
